update `board` set `active` = case when `active` = 't' then '1' when `active`='f' then '0' end;
update `custom_field` set `multiple` = case when `multiple` = 't' then '1' when `multiple`='f' then '0' end, `required` = case when `required` = 't' then '1' when `required`='f' then '0' end, `show_on_create` = case when `show_on_create` = 't' then '1' when `show_on_create`='f' then '0' end;
update `ipwhite_blacklist` set `api_only` = case when `api_only` = 't' then '1' when `api_only`='f' then '0' end, `enabled` = case when `enabled` = 't' then '1' when `enabled`='f' then '0' end, `white_list` = case when `white_list` = 't' then '1' when `white_list`='f' then '0' end;
update `issue_filter` set `open` = case when `open` = 't' then '1' when `open`='f' then '0' end;
update `issue_mentions` set `link` = case when `link` = 't' then '1' when `link`='f' then '0' end, `mention` = case when `mention` = 't' then '1' when `mention`='f' then '0' end;
update `issue_type` set `active` = case when `active` = 't' then '1' when `active`='f' then '0' end;
update `jd_group` set `all_users` = case when `all_users` = 't' then '1' when `all_users`='f' then '0' end;
update `jd_user` set `active` = case when `active` = 't' then '1' when `active`='f' then '0' end, `api_enabled` = case when `api_enabled` = 't' then '1' when `api_enabled`='f' then '0' end, `email_notification` = case when `email_notification` = 't' then '1' when `email_notification`='f' then '0' end, `locked` = case when `locked` = 't' then '1' when `locked`='f' then '0' end, `mfa_enabled` = case when `mfa_enabled` = 't' then '1' when `mfa_enabled`='f' then '0' end, `pending_activation` = case when `pending_activation` = 't' then '1' when `pending_activation`='f' then '0' end, `slack_enabled` = case when `slack_enabled` = 't' then '1' when `slack_enabled`='f' then '0' end, `slack_notification` = case when `slack_notification` = 't' then '1' when `slack_notification`='f' then '0' end, `super_admin` = case when `super_admin` = 't' then '1' when `super_admin`='f' then '0' end;
update `jdconfiguration` set `boolean_value` = case when `boolean_value` = 't' then '1' when `boolean_value`='f' then '0' end;
update `jdscheduler` set `active` = case when `active` = 't' then '1' when `active`='f' then '0' end;
update `page` set `has_child` = case when `has_child` = 't' then '1' when `has_child`='f' then '0' end;
update `project` set `active` = case when `active` = 't' then '1' when `active`='f' then '0' end, `notify_via_slack` = case when `notify_via_slack` = 't' then '1' when `notify_via_slack`='f' then '0' end;
update `repository` set `active` = case when `active` = 't' then '1' when `active`='f' then '0' end;
update `task` set `completed` = case when `completed` = 't' then '1' when `completed`='f' then '0' end;
update `time_tracking` set `enabled` = case when `enabled` = 't' then '1' when `enabled`='f' then '0' end;
update `version` set `released` = case when `released` = 't' then '1' when `released`='f' then '0' end;
update `web_hook` set `active` = case when `active` = 't' then '1' when `active`='f' then '0' end, `all_events` = case when `all_events` = 't' then '1' when `all_events`='f' then '0' end, `all_projects` = case when `all_projects` = 't' then '1' when `all_projects`='f' then '0' end;
update `wiki_folder` set `has_child_folders` = case when `has_child_folders` = 't' then '1' when `has_child_folders`='f' then '0' end, `project_default` = case when `project_default` = 't' then '1' when `project_default`='f' then '0' end;
update `workflow_transition` set `from_all` = case when `from_all` = 't' then '1' when `from_all`='f' then '0' end, `initial` = case when `initial` = 't' then '1' when `initial`='f' then '0' end;

SET foreign_key_checks = 0;

ALTER TABLE `attachment` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `authority_global` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `authority_project` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `lane` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `board` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT, MODIFY COLUMN `active` tinyint;
ALTER TABLE `comment` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `git_branch` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `git_commit` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `git_hook` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_history` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_mentions` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_other_relationship` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_relationship` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_search_query` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_search_query_rule` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_status` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_type` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_view` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `jdscheduler` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `jdscheduler_job_data` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `relationship` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `repository` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `resolution` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `task` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `version` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `watchers` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `work_log` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `workflow` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `workflow_step` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `workflow_transition` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `workflow_transition_properties` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `jd_token` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_event` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `jd_user` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `jd_group` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `label` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `project` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `time_tracking` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `custom_field` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `jdevent` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `subscription` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `authority` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `ipwhite_blacklist` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `password_reset_token` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `issue_filter` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `page` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `page_attachment` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `page_revision` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `jd_global_group` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `jdconfiguration` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `web_hook` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `web_hook_headers` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `web_hook_log` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `wiki` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `wiki_attachment` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `wiki_folder` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;
ALTER TABLE `wiki_revision` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT;

ALTER TABLE `board` MODIFY COLUMN `active` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `custom_field` MODIFY COLUMN `multiple` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `required` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `show_on_create` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `ipwhite_blacklist` MODIFY COLUMN `api_only` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `enabled` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `white_list` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `issue_filter` MODIFY COLUMN `open` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `issue_mentions` MODIFY COLUMN `link` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `mention` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `issue_type` MODIFY COLUMN `active` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `jd_group` MODIFY COLUMN `all_users` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `jd_user` MODIFY COLUMN `active` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `api_enabled` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `email_notification` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `locked` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `mfa_enabled` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `pending_activation` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `slack_enabled` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `slack_notification` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `super_admin` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `jdconfiguration` MODIFY COLUMN `boolean_value` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `jdscheduler` MODIFY COLUMN `active` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `page` MODIFY COLUMN `has_child` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `project` MODIFY COLUMN `active` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `notify_via_slack` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `repository` MODIFY COLUMN `active` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `task` MODIFY COLUMN `completed` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `time_tracking` MODIFY COLUMN `enabled` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `version` MODIFY COLUMN `released` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `web_hook` MODIFY COLUMN `active` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `all_events` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `all_projects` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `wiki_folder` MODIFY COLUMN `has_child_folders` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `project_default` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `workflow_transition` MODIFY COLUMN `from_all` tinyint NOT NULL DEFAULT 0, MODIFY COLUMN `initial` tinyint NOT NULL DEFAULT 0;

SET foreign_key_checks = 1;
